language: objective-c

env:
  matrix:
   - NODE_NVM_VERSION="0.10" RUN_BUILD="static_build"
   - NODE_NVM_VERSION="0.8" RUN_BUILD="static_build"
   - NODE_NVM_VERSION="0.10" RUN_BUILD="shared_build"
   - NODE_NVM_VERSION="0.8" RUN_BUILD="shared_build"
  global:
   - secure: LvrV5lifkIM99Wz0G0jqxC3uqGYIYz4hgM0oeB0MsPmQ62l8+CfIURqcFlfKSb+0s0YP2mAeacSno8oTpSZoWP27sTJutYmyk0jeVUHKQqwQClkloeErOfyLVnYijUTAX/J1Blgl+fhfvGtZE/dBIk/XEa6tEKmF0kv7z6GKVz8=
   - secure: hNMAfx4uCD8P5ycw7en9WbPFxd9Z4i8LmuClPC6lYYBTf/3lsHbtO5oRVmqFQevlZbFoPt1OU1pr4Pnj7iQsYnezc3YBevXQNsv0UvMlQAzwmW2cQOuRjHZ5TXEEMAQBbiWO0BOeQrC6m46wkQbkuzX1XpxRnaXhdhd/FeZxVwk=
   - secure: Atz+Zcl9Faw1OvUEv5vK3aYXGWQS8dvDd4nLQ/2XU0doVKjsNvFxVWtBFvE91yvbnJnkSR6IrD6U4I3RQkmaEZ4s37nipHZ1nkuPlSucV0SamAwOcO4Wm+D0yrlPAt/bDQHlAojY1UE98U0oqDKfkBvLwdzIGvv0qISR/W/8rLI=

before_install:
# put node-pre-gyp on path
- export PATH=./node_modules/.bin/:$PATH
- echo $NODE_NVM_VERSION
- git clone https://github.com/creationix/nvm.git ../.nvm
- source ../.nvm/nvm.sh
- nvm install $NODE_NVM_VERSION
- nvm use $NODE_NVM_VERSION
- node --version
- npm --version

install:
- CURRENT_DIR=`pwd`
# WARNING: this script modifies the environment
- source ./util/${RUN_BUILD}.sh
- cd $CURRENT_DIR

before_script:
- npm install mocha

before_script:
- npm install --build-from-source

script:
- make test
- PUBLISH_BINARY=false
- if [ "[publish-binary]" = `git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n'` ]; then echo PUBLISH_BINARY;PUBLISH_BINARY=true; fi;
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]] && [[ $RUN_BUILD == "static_build" ]]; then echo PUBLISH_BINARY;PUBLISH_BINARY=true; fi;
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi
- node-pre-gyp clean
- if [[ $PUBLISH_BINARY == true ]]; then npm install --fallback-to-build=false; fi
- node-pre-gyp clean
# TODO - unpublish binary if this failed

after_success:
# publish to npm if this is a tag
- PUBLISH=false
- npm config set email dane@dbsgeo.com
- npm config set _auth $NPM_AUTH
- echo $RUN_BUILD
- echo $NODE_VERSION
- echo $NODE_NVM_VERSION
- echo `git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n'`
- if [[ $RUN_BUILD == "static_build" ]] && [[ $NODE_NVM_VERSION == "0.8" ]] && [ "[publish]" = `git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n'` ]; then echo "publish"; PUBLISH=true; fi;
- if [[ $RUN_BUILD == "static_build" ]] && [[ $NODE_NVM_VERSION == "0.8" ]] && [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then echo "publish"; PUBLISH=true; fi;
- if [[ $PUBLISH == true ]]; then echo "publishing"; npm publish; fi;
